[package]
name = "database"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
rusqlite = "0.26.2"
actix-web = "4"
actix-cors = "0.7.1"
actix-files = "0.6.6"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
